Fix: Move config to src folder to resolve import error
Problem: React build doesn't allow imports outside src/ directory
Error: 'You attempted to import ../../config.environment which falls outside of the project src/'

Solution:
- Moved config.environment.js to src/config.js
- Updated Dashboard.js import from '../../config.environment' to '../config'

This allows the config file to be within the src/ directory as required by react-scripts.